config: !!python/object:code.classifier.Config
  backbone_name: google/vit-base-patch16-224
  batch_size: 32
  dropout: 0.3
  frozen_lr: null
  gradually_unfreeze: false
  image_res: 224
  image_type: 3
  learning_rate: 1.0e-05
  max_epochs: 50
  model_name: vit-base-patch16-224
  num_layers_to_unfreeze: null
  num_workers: 16
  optimizer_name: adam
  patience: 10
  transfer_learning: true
  unfreeze_interval: null
  unfrozen_lr: null
  use_class_weights: true
  version: '001'
  weight_decay: 1.0e-05
