config: !!python/object:code.classifier.Config
  backbone_name: google/vit-base-patch32-384
  batch_size: 16
  dropout: 0.3
  frozen_lr: 1.0e-06
  gradually_unfreeze: true
  image_res: 384
  image_type: 3
  learning_rate: 1.0e-05
  max_epochs: 5
  model_name: Vit_patch32_optimization
  num_layers_to_unfreeze: 2
  num_workers: 16
  optimizer_name: adam
  patience: 10
  transfer_learning: true
  unfreeze_interval: 5
  unfrozen_lr: 1.0e-05
  use_class_weights: true
  version: '001'
  weight_decay: 1.0e-05
