config: !!python/object:code.classifier.Config
  backbone_name: efficientnet_b3
  batch_size: 20
  dropout: 0.2
  frozen_lr: 1.0e-05
  gradually_unfreeze: true
  image_res: 300
  image_type: 3
  learning_rate: 0.0001
  max_epochs: 50
  model_name: EfficientNetB3_gradual_unfreeze
  num_layers_to_unfreeze: 2
  num_workers: 16
  optimizer_name: adam
  patience: 5
  transfer_learning: true
  unfreeze_interval: 5
  unfrozen_lr: 0.0001
  use_class_weights: true
  version: '001'
  weight_decay: 0.0001
