config: !!python/object:code.classifier.Config
  backbone_name: resnet50
  batch_size: 20
  dropout: 0.2
  frozen_lr: null
  gradually_unfreeze: false
  image_res: 224
  image_type: 3
  learning_rate: 0.0001
  max_epochs: 50
  model_name: ResNet50_unfreeze
  num_layers_to_unfreeze: null
  num_workers: 16
  optimizer_name: sgd
  patience: 10
  transfer_learning: false
  unfreeze_interval: null
  unfrozen_lr: null
  use_class_weights: true
  version: '001'
  weight_decay: 0.0001
